name: Import Testnet Validators

on:
  workflow_dispatch:

jobs:
  trigger-testnet:
    uses: ./.github/workflows/import-validators.yml
    with:
      network: testnet
      api_url: https://validators-api-testnet.nuxt.dev
      validators_path: public/validators/test-albatross
