name: Sync Mainnet

on:
  workflow_dispatch:
  schedule:
    - cron: '35 * * * *' # Election block are produced every 12 hours at 00:38 and 12:38

jobs:
  mainnet:
    needs: []
    uses: ./.github/workflows/sync.yml
    with:
      network: mainnet
      api_url: 'https://validators-api-mainnet.nuxt.dev'
