name: Sync Testnet

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  testnet:
    needs: []
    uses: ./.github/workflows/sync.yml
    with:
      network: testnet
      api_url: 'https://validators-api-testnet.nuxt.dev'
